const en = {
    // Header
    "home": "Home",
    "about": "About",
    
    // Main content
    "title": "M3U8 Online Player",
    "url_placeholder": "Please enter M3U8 playback address",
    "play_button": "Play",
    
    // Embed section
    "embed_website": "Embed in website:",
    "embed_code": "Embed code:",
    
    // Description
    "description": "M3U8Player is a Chrome browser extension tool that implements HTTP Live Streaming client. You can play .m3u8 HTTP Live Streaming (HLS). It relies on HTML5 video and Media Source Extensions for playback. It works by converting MPEG-2 transport streams and AAC/MP3 streams into ISO BMFF (MP4) segments. If there are Web Workers in the browser, they can be used to perform transcoding asynchronously. It also supports HLS + fmp4.",
    
    // What is M3U8 section
    "what_is_m3u8": "What is an M3U8 file?",
    "m3u8_explanation": "Files with the M3U8 extension are UTF-8 encoded audio playlist files. They are plain text files that both audio and video players can use to describe the location of media files.",
    "m3u8_example": "For example, an M3U8 file might provide online file references for an internet radio station. Another file might be created on your computer to establish a playlist for your personal music or a series of videos.",
    "m3u8_effect": "Either way, the effect is the same: you can open the file and quickly and easily start playing the content that the playlist points to. If you find yourself wanting to listen to the same song repeatedly, you can create an M3U8 file as a shortcut to play those specific tracks in your media player.",
    "m3u8_paths": "Files can use absolute paths, relative paths, and URLs to point to specific media files and/or entire folders of media files. Other information in the file might be comments describing the content of the file.",
    "m3u8_format": "M3U8 is a file format for playing multimedia playlists. It was originally designed to play audio files like MP3, but more and more software now uses it to play video file playlists. M3U8 can also specify online streaming audio sources. Many players and software support the M3U8 file format.",
    
    // Quote
    "quote": "If something is important enough, even if the odds are against you, you should still do it.",
    "quote_author": "Elon Musk",
    
    // Footer
    "copyright": "© 2019 - 2025",
    "disclaimer": "Resources come from the internet. If there is any infringement, please contact customer service for deletion!",
    "friendly_links": "Friendly Links:",
    
    // Language switcher
    "language": "Language",
    "english": "English",
    "french": "Français",
    "chinese": "中文",
    
    // About page
    "about_title": "About Us",
    "about_subtitle": "Professional M3U8 streaming player development team, committed to providing users with the best viewing experience",
    "our_story": "Our Story",
    "story_content_1": "The M3U8 Player project started in 2019, when we noticed a lack of simple, easy-to-use, and powerful M3U8 streaming players in the market.",
    "story_content_2": "Our team consists of experienced developers focused on creating user-friendly tools that allow anyone to easily play M3U8 format media files.",
    "story_content_3": "After years of development and optimization, we continuously improve product features, ensuring compatibility and stability, providing users with the best viewing experience.",
    "our_mission": "Our Mission",
    "mission_content_1": "Our mission is to simplify the M3U8 streaming playback experience, ensuring that technology doesn't become a barrier for users to enjoy high-quality media content.",
    "mission_content_2": "We are committed to developing open-source, free tools that support multiple formats, ensure cross-platform compatibility, and provide users with professional-level playback experience.",
    "mission_content_3": "Through continuous innovation and user feedback, we continuously optimize our products, making M3U8 Player the preferred tool for streaming playback.",
    "key_features": "Key Features",
    "feature_speed": "High-Speed Playback",
    "feature_speed_desc": "Optimized playback engine ensures smooth viewing experience",
    "feature_compatibility": "Wide Compatibility",
    "feature_compatibility_desc": "Supports multiple browsers and devices, cross-platform compatible",
    "feature_customization": "Highly Customizable",
    "feature_customization_desc": "Rich settings options to meet personalized needs",
    "development_team": "Development Team",
    "team_description": "Our team consists of developers who love technology, with rich experience in streaming media and web development. We believe in the power of open source and are committed to contributing quality tools to the community.",
    "team_role_1": "Frontend Development",
    "team_role_1_desc": "User Experience Expert",
    "team_role_2": "Backend Development",
    "team_role_2_desc": "System Architect",
    "team_role_3": "Product Design",
    "team_role_3_desc": "User Experience Designer",
    "contact_us": "Contact Us",
    "contact_description": "If you have any questions, suggestions, or feedback, please feel free to contact us. We value every user's opinion.",
    "email_us": "Send Email",
    "github": "GitHub",
    
    // Privacy page
    "privacy": "Privacy Policy",
    "privacy_title": "Privacy Policy",
    "privacy_subtitle": "We value your privacy. This policy explains how we collect, use, and protect your personal information",
    "last_updated": "Last Updated: December 2024",
    "information_collection": "Information Collection",
    "collection_content_1": "The types of information we collect include:",
    "collection_item_1": "Usage Data: We collect information about how you use our services, including access times, page views, etc.",
    "collection_item_2": "Device Information: Browser type, operating system version, device identifiers, etc.",
    "collection_item_3": "Log Information: Server logs, error reports, etc.",
    "collection_content_2": "We do not collect your personal identification information such as name, address, phone number, or email address unless you actively provide it.",
    "information_usage": "Information Usage",
    "usage_content_1": "We use the collected information to provide and improve services, handle user requests, and send important notifications.",
    "usage_item_1": "Provide and improve our services",
    "usage_item_2": "Analyze usage patterns to optimize user experience",
    "usage_item_3": "Detect and prevent fraud or abuse",
    "usage_item_4": "Comply with legal obligations",
    "information_sharing": "Information Sharing",
    "sharing_content_1": "We will not sell, trade, or otherwise transfer your personal information to third parties unless:",
    "sharing_item_1": "We obtain your explicit consent",
    "sharing_item_2": "Required by law or government agencies",
    "sharing_item_3": "To protect our rights, property, or safety",
    "sharing_content_2": "We may share information with trusted third-party service providers who help us operate our website and provide services.",
    "data_security": "Data Security",
    "security_content_1": "We implement appropriate technical and organizational security measures to protect your information, including:",
    "security_item_1": "Using encryption technology to protect data transmission",
    "security_item_2": "Regular security assessments and updates",
    "security_item_3": "Limiting employee access to personal information",
    "security_item_4": "Monitoring and detecting security threats",
    "security_content_2": "While we strive to protect your information, please note that internet transmission or electronic storage methods are not 100% secure.",
    "cookies_usage": "Cookie Usage",
    "cookies_content_1": "We use cookies and similar technologies to:",
    "cookies_item_1": "Remember your preference settings",
    "cookies_item_2": "Analyze website traffic and usage patterns",
    "cookies_item_3": "Provide personalized experience",
    "cookies_item_4": "Improve our services",
    "cookies_content_2": "You can control cookie usage through browser settings, but disabling certain cookies may affect website functionality.",
    "third_party_services": "Third-Party Services",
    "third_party_content_1": "Our services may contain third-party links or services, including:",
    "third_party_item_1": "Analytics services (such as Google Analytics)",
    "third_party_item_2": "Social media plugins",
    "third_party_item_3": "Payment processing services",
    "third_party_content_2": "These third-party services have their own privacy policies, and we are not responsible for their privacy practices. We recommend reading the privacy policies of these third-party services.",
    "children_privacy": "Children's Privacy",
    "children_content_1": "Our services are not directed to children under 13 years of age. We do not knowingly collect personal information from children under 13.",
    "children_content_2": "If you are a parent or guardian and you know that your child has provided us with personal information, please contact us. If we discover that we have collected personal information from children under 13, we will take steps to delete such information.",
    "privacy_rights": "Your Privacy Rights",
    "rights_content_1": "Under applicable law, you may have the following rights:",
    "rights_item_1": "Access personal information we hold about you",
    "rights_item_2": "Correct inaccurate or incomplete personal information",
    "rights_item_3": "Delete your personal information",
    "rights_item_4": "Restrict or object to processing your personal information",
    "rights_item_5": "Data portability",
    "rights_content_2": "To exercise these rights, please contact us through the contact information provided at the end of this policy.",
    "policy_changes": "Policy Changes",
    "changes_content_1": "We may update this privacy policy from time to time. When we make significant changes, we will:",
    "changes_item_1": "Post the updated policy on our website",
    "changes_item_2": "Update the 'Last Updated' date",
    "changes_item_3": "Notify you by email when appropriate",
    "changes_content_2": "We recommend reviewing this policy regularly to understand any changes. Continued use of our services indicates your acceptance of the updated policy.",
    "contact_privacy": "Privacy Questions Contact",
    "contact_privacy_desc": "If you have any questions or concerns about this privacy policy, please contact us through the following methods:",
    "email": "Email:",
    "response_time": "Response Time:",
    "response_time_desc": "We will respond within 48 hours of receiving your request",

    // Additional keys for About page
    "feature_1": "Support multiple video formats",
    "feature_2": "Cross-platform compatibility",
    "feature_3": "HD streaming support",
    "feature_4": "User-friendly interface",
    "team_content_1": "Our development team is composed of experienced engineers focused on frontend technology, streaming, and user experience design.",
    "team_content_2": "We continuously follow technology trends and optimize product performance to ensure the best viewing experience.",
    "team_content_3": "Through open-source collaboration and community feedback, we keep improving features to provide better service.",
    "contact_content": "If you have any questions or suggestions, please contact us via:",
    "discord": "Discord",

    // Additional keys for Privacy page
    "user_rights": "User Rights",
    "privacy_contact_content": "If you have any questions about our privacy policy or need to exercise your rights, please contact us via the methods below:",
    "privacy_email": "Privacy Email",
    "support_email": "Support Email",
    "collection_content_3": "Usage data includes access times, feature usage, and error logs, used to improve product and service quality.",
    "security_content_3": "Although we take reasonable security measures, we cannot guarantee 100% security, and we continuously improve our protections.",
    "rights_content_3": "In some cases, we may need to verify your identity before processing related requests",
    "usage_content_1": "We use the collected information to provide and improve services, handle user requests, and send important notifications.",
    "usage_content_2": "We will not sell, rent, or share your personal information with third parties unless we obtain your explicit consent.",
    "usage_content_3": "When necessary, we may share information with third parties required by law or related to protecting user rights."
};
