const fr = {
    // Header
    "home": "Accueil",
    "about": "À propos",
    
    // Main content
    "title": "Lecteur M3U8 en ligne",
    "url_placeholder": "Veuillez entrer l'adresse de lecture M3U8",
    "play_button": "Jouer",
    
    // Embed section
    "embed_website": "Intégrer dans le site web :",
    "embed_code": "Code d'intégration :",
    
    // Description
    "description": "M3U8Player est un outil d'extension Chrome qui implémente un client de streaming HTTP en direct. Vous pouvez lire des fichiers .m3u8 HTTP Live Streaming (HLS). Il s'appuie sur la vidéo HTML5 et les extensions de source multimédia pour la lecture. Il fonctionne en convertissant les flux de transport MPEG-2 et les flux AAC/MP3 en segments ISO BMFF (MP4). S'il y a des Web Workers dans le navigateur, ils peuvent être utilisés pour effectuer le transcodage de manière asynchrone. Il prend également en charge HLS + fmp4.",
    
    // What is M3U8 section
    "what_is_m3u8": "Qu'est-ce qu'un fichier M3U8 ?",
    "m3u8_explanation": "Les fichiers avec l'extension M3U8 sont des fichiers de liste de lecture audio encodés en UTF-8. Ce sont des fichiers texte brut que les lecteurs audio et vidéo peuvent utiliser pour décrire l'emplacement des fichiers multimédia.",
    "m3u8_example": "Par exemple, un fichier M3U8 pourrait fournir des références de fichiers en ligne pour une station de radio Internet. Un autre fichier pourrait être créé sur votre ordinateur pour établir une liste de lecture pour votre musique personnelle ou une série de vidéos.",
    "m3u8_effect": "Dans tous les cas, l'effet est le même : vous pouvez ouvrir le fichier et commencer rapidement et facilement à lire le contenu vers lequel pointe la liste de lecture. Si vous vous trouvez à vouloir écouter la même chanson à plusieurs reprises, vous pouvez créer un fichier M3U8 comme raccourci pour lire ces pistes spécifiques dans votre lecteur multimédia.",
    "m3u8_paths": "Les fichiers peuvent utiliser des chemins absolus, des chemins relatifs et des URL pour pointer vers des fichiers multimédia spécifiques et/ou des dossiers entiers de fichiers multimédia. D'autres informations dans le fichier peuvent être des commentaires décrivant le contenu du fichier.",
    "m3u8_format": "M3U8 est un format de fichier pour lire des listes de lecture multimédia. Il a été conçu à l'origine pour lire des fichiers audio comme MP3, mais de plus en plus de logiciels l'utilisent maintenant pour lire des listes de fichiers vidéo. M3U8 peut également spécifier des sources audio de streaming en ligne. De nombreux lecteurs et logiciels prennent en charge le format de fichier M3U8.",
    
    // Quote
    "quote": "Si quelque chose est assez important, même si les chances sont contre vous, vous devriez quand même le faire.",
    "quote_author": "Elon Musk",
    
    // Footer
    "copyright": "© 2019 - 2025",
    "disclaimer": "Les ressources proviennent d'Internet. S'il y a violation des droits d'auteur, veuillez contacter le service client pour suppression !",
    "friendly_links": "Liens amis :",
    
    // Language switcher
    "language": "Langue",
    "english": "English",
    "french": "Français",
    "chinese": "中文",
    
    // About page
    "about_title": "À propos de nous",
    "about_subtitle": "Équipe de développement professionnelle du lecteur M3U8, engagée à fournir aux utilisateurs la meilleure expérience de visionnage",
    "our_story": "Notre histoire",
    "story_content_1": "Le projet M3U8 Player a commencé en 2019, lorsque nous avons remarqué un manque de lecteurs M3U8 simples, faciles à utiliser et puissants sur le marché.",
    "story_content_2": "Notre équipe se compose de développeurs expérimentés axés sur la création d'outils conviviaux qui permettent à quiconque de lire facilement des fichiers multimédias au format M3U8.",
    "story_content_3": "Après des années de développement et d'optimisation, nous améliorons continuellement les fonctionnalités du produit, en assurant la compatibilité et la stabilité, en fournissant aux utilisateurs la meilleure expérience de visionnage.",
    "our_mission": "Notre mission",
    "mission_content_1": "Notre mission est de simplifier l'expérience de lecture de streaming M3U8, en s'assurant que la technologie ne devienne pas un obstacle pour les utilisateurs pour profiter du contenu multimédia de haute qualité.",
    "mission_content_2": "Nous nous engageons à développer des outils open source et gratuits qui prennent en charge plusieurs formats, assurent la compatibilité multiplateforme et fournissent aux utilisateurs une expérience de lecture de niveau professionnel.",
    "mission_content_3": "Grâce à l'innovation continue et aux commentaires des utilisateurs, nous optimisons continuellement nos produits, faisant du M3U8 Player l'outil préféré pour la lecture de streaming.",
    "key_features": "Fonctionnalités clés",
    "feature_speed": "Lecture haute vitesse",
    "feature_speed_desc": "Moteur de lecture optimisé garantit une expérience de visionnage fluide",
    "feature_compatibility": "Large compatibilité",
    "feature_compatibility_desc": "Prend en charge plusieurs navigateurs et appareils, compatible multiplateforme",
    "feature_customization": "Hautement personnalisable",
    "feature_customization_desc": "Options de paramètres riches pour répondre aux besoins personnalisés",
    "development_team": "Équipe de développement",
    "team_description": "Notre équipe se compose de développeurs qui aiment la technologie, avec une riche expérience dans le développement de médias en streaming et web. Nous croyons au pouvoir de l'open source et nous nous engageons à contribuer des outils de qualité à la communauté.",
    "team_role_1": "Développement frontend",
    "team_role_1_desc": "Expert en expérience utilisateur",
    "team_role_2": "Développement backend",
    "team_role_2_desc": "Architecte système",
    "team_role_3": "Conception de produit",
    "team_role_3_desc": "Concepteur d'expérience utilisateur",
    "contact_us": "Contactez-nous",
    "contact_description": "Si vous avez des questions, des suggestions ou des commentaires, n'hésitez pas à nous contacter. Nous valorisons l'opinion de chaque utilisateur.",
    "email_us": "Envoyer un email",
    "github": "GitHub",
    
    // Privacy page
    "privacy": "Politique de confidentialité",
    "privacy_title": "Politique de confidentialité",
    "privacy_subtitle": "Nous valorisons votre vie privée. Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles",
    "last_updated": "Dernière mise à jour : Décembre 2024",
    "information_collection": "Collecte d'informations",
    "collection_content_1": "Les types d'informations que nous collectons incluent :",
    "collection_item_1": "Données d'utilisation : Nous collectons des informations sur la façon dont vous utilisez nos services, y compris les heures d'accès, les vues de pages, etc.",
    "collection_item_2": "Informations sur l'appareil : Type de navigateur, version du système d'exploitation, identifiants d'appareil, etc.",
    "collection_item_3": "Informations de journal : Journaux du serveur, rapports d'erreur, etc.",
    "collection_content_2": "Nous ne collectons pas vos informations d'identification personnelle telles que le nom, l'adresse, le numéro de téléphone ou l'adresse e-mail, sauf si vous les fournissez activement.",
    "information_usage": "Utilisation des informations",
    "usage_content_1": "Nous utilisons les informations collectées pour fournir et améliorer les services, traiter les demandes des utilisateurs et envoyer des notifications importantes.",
    "usage_item_1": "Fournir et améliorer nos services",
    "usage_item_2": "Analyser les modèles d'utilisation pour optimiser l'expérience utilisateur",
    "usage_item_3": "Détecter et prévenir la fraude ou les abus",
    "usage_item_4": "Se conformer aux obligations légales",
    "information_sharing": "Partage d'informations",
    "sharing_content_1": "Nous ne vendrons, n'échangerons ni ne transférerons autrement vos informations personnelles à des tiers, sauf si :",
    "sharing_item_1": "Nous obtenons votre consentement explicite",
    "sharing_item_2": "Requis par la loi ou les agences gouvernementales",
    "sharing_item_3": "Pour protéger nos droits, notre propriété ou notre sécurité",
    "sharing_content_2": "Nous pouvons partager des informations avec des fournisseurs de services tiers de confiance qui nous aident à exploiter notre site web et à fournir des services.",
    "data_security": "Sécurité des données",
    "security_content_1": "Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles appropriées pour protéger vos informations, y compris :",
    "security_item_1": "Utilisation de la technologie de cryptage pour protéger la transmission des données",
    "security_item_2": "Évaluations de sécurité régulières et mises à jour",
    "security_item_3": "Limitation de l'accès des employés aux informations personnelles",
    "security_item_4": "Surveillance et détection des menaces de sécurité",
    "security_content_2": "Bien que nous nous efforcions de protéger vos informations, veuillez noter que la transmission Internet ou les méthodes de stockage électronique ne sont pas 100% sécurisées.",
    "cookies_usage": "Utilisation des cookies",
    "cookies_content_1": "Nous utilisons des cookies et des technologies similaires pour :",
    "cookies_item_1": "Mémoriser vos paramètres de préférence",
    "cookies_item_2": "Analyser le trafic du site web et les modèles d'utilisation",
    "cookies_item_3": "Fournir une expérience personnalisée",
    "cookies_item_4": "Améliorer nos services",
    "cookies_content_2": "Vous pouvez contrôler l'utilisation des cookies via les paramètres du navigateur, mais désactiver certains cookies peut affecter la fonctionnalité du site web.",
    "third_party_services": "Services tiers",
    "third_party_content_1": "Nos services peuvent contenir des liens ou services tiers, y compris :",
    "third_party_item_1": "Services d'analyse (tels que Google Analytics)",
    "third_party_item_2": "Plugins de médias sociaux",
    "third_party_item_3": "Services de traitement des paiements",
    "third_party_content_2": "Ces services tiers ont leurs propres politiques de confidentialité, et nous ne sommes pas responsables de leurs pratiques de confidentialité. Nous recommandons de lire les politiques de confidentialité de ces services tiers.",
    "children_privacy": "Confidentialité des enfants",
    "children_content_1": "Nos services ne sont pas destinés aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d'informations personnelles auprès d'enfants de moins de 13 ans.",
    "children_content_2": "Si vous êtes un parent ou un tuteur et que vous savez que votre enfant nous a fourni des informations personnelles, veuillez nous contacter. Si nous découvrons que nous avons collecté des informations personnelles auprès d'enfants de moins de 13 ans, nous prendrons des mesures pour supprimer ces informations.",
    "privacy_rights": "Vos droits à la confidentialité",
    "rights_content_1": "Selon la loi applicable, vous pouvez avoir les droits suivants :",
    "rights_item_1": "Accéder aux informations personnelles que nous détenons sur vous",
    "rights_item_2": "Corriger les informations personnelles inexactes ou incomplètes",
    "rights_item_3": "Supprimer vos informations personnelles",
    "rights_item_4": "Restreindre ou s'opposer au traitement de vos informations personnelles",
    "rights_item_5": "Portabilité des données",
    "rights_content_2": "Pour exercer ces droits, veuillez nous contacter via les informations de contact fournies à la fin de cette politique.",
    "policy_changes": "Changements de politique",
    "changes_content_1": "Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. Lorsque nous apportons des changements importants, nous :",
    "changes_item_1": "Publions la politique mise à jour sur notre site web",
    "changes_item_2": "Mettons à jour la date de 'Dernière mise à jour'",
    "changes_item_3": "Vous notifions par e-mail le cas échéant",
    "changes_content_2": "Nous recommandons de réviser cette politique régulièrement pour comprendre tout changement. L'utilisation continue de nos services indique votre acceptation de la politique mise à jour.",
    "contact_privacy": "Contact pour questions de confidentialité",
    "contact_privacy_desc": "Si vous avez des questions ou des préoccupations concernant cette politique de confidentialité, veuillez nous contacter via les méthodes suivantes :",
    "email": "E-mail :",
    "response_time": "Temps de réponse :",
    "response_time_desc": "Nous répondrons dans les 48 heures suivant la réception de votre demande",

    // Clés supplémentaires pour la page À propos
    "feature_1": "Prend en charge plusieurs formats vidéo",
    "feature_2": "Compatibilité multiplateforme",
    "feature_3": "Prise en charge du streaming HD",
    "feature_4": "Interface conviviale",
    "team_content_1": "Notre équipe de développement est composée d'ingénieurs expérimentés, spécialisés en technologies frontend, streaming et conception d'expérience utilisateur.",
    "team_content_2": "Nous suivons en continu les tendances technologiques et optimisons les performances du produit afin d'assurer la meilleure expérience de visionnage.",
    "team_content_3": "Grâce à la collaboration open source et aux retours de la communauté, nous améliorons sans cesse les fonctionnalités pour offrir un meilleur service.",
    "contact_content": "Si vous avez des questions ou des suggestions, veuillez nous contacter via :",
    "discord": "Discord",

    // Clés supplémentaires pour la page Confidentialité
    "user_rights": "Droits des utilisateurs",
    "privacy_contact_content": "Si vous avez des questions concernant notre politique de confidentialité ou si vous devez exercer vos droits, veuillez nous contacter via les méthodes ci-dessous :",
    "privacy_email": "E-mail confidentialité",
    "support_email": "E-mail support",
    "collection_content_3": "Les données d'utilisation incluent les heures d'accès, l'utilisation des fonctionnalités et les journaux d'erreurs, utilisées pour améliorer la qualité des produits et services.",
    "security_content_3": "Bien que nous prenions des mesures de sécurité raisonnables, nous ne pouvons pas garantir une sécurité à 100 %, et nous améliorons continuellement nos protections.",
    "rights_content_3": "Dans certains cas, nous pouvons devoir vérifier votre identité avant de traiter les demandes concernées",

    // Compléments : paragraphes d'utilisation sur privacy.html
    "usage_content_1": "Nous utilisons les informations collectées pour fournir et améliorer les services, traiter les demandes des utilisateurs et envoyer des notifications importantes.",
    "usage_content_2": "Nous ne vendrons pas, ne louerons pas et ne partagerons pas vos informations personnelles avec des tiers sans votre consentement explicite.",
    "usage_content_3": "Lorsque cela est nécessaire, nous pouvons partager des informations avec des tiers requis par la loi ou liés à la protection des droits des utilisateurs."
};
