const zh = {
    // Header
    "home": "首页",
    "about": "关于",
    
    // Main content
    "title": "m3u8在线播放器",
    "url_placeholder": "请输入m3u8播放地址",
    "play_button": "播放",
    
    // Embed section
    "embed_website": "嵌入网站:",
    "embed_code": "嵌入代码:",
    
    // Description
    "description": "M3U8Player 是一款实现 HTTP 实时流客户端的 Chrome 浏览器扩展工具。你可以播放 .m3u8 HTTP Live Streaming (HLS)。它依靠 HTML5 视频和媒体源扩展进行播放。它的工作原理是将 MPEG-2 传输流和 AAC/MP3 流转换成 ISO BMFF (MP4) 片段。如果浏览器中有 Web Worker，可使用它异步执行转码。它还支持 HLS + fmp4。",
    
    // What is M3U8 section
    "what_is_m3u8": "什么是m3u8文件?",
    "m3u8_explanation": "文件扩展名为 M3U8 的文件是一种 UTF-8 编码的音频播放列表文件。它们是纯文本文件，音频和视频播放器都可以用它们来描述媒体文件的位置。",
    "m3u8_example": "例如，一个 M3U8 文件可能会提供互联网电台的在线文件参考。另一个文件可能是在你的电脑上创建的，用于为你的个人音乐或一系列视频建立播放列表。",
    "m3u8_effect": "无论哪种方式，效果都是一样的：你可以打开文件，快速轻松地开始播放播放列表指向的内容。如果你发现自己想反复听同一首歌，你可以制作一个 M3U8 文件，作为在媒体播放器中播放这些特定曲目的快捷方式。",
    "m3u8_paths": "文件可以使用绝对路径、相对路径和 URL 来指向特定的媒体文件和/或媒体文件的整个文件夹。文件中的其他信息可能是描述文件内容的注释。",
    "m3u8_format": "M3U8是一种播放多媒体列表的文件格式，它的设计初衷是为了播放音频文件，比如MP3，但是越来越多的软件现在用来播放视频文件列表，M3U8也可以指定在线流媒体音频源。很多播放器和软件都支持M3U8文件格式。",
    
    // Quote
    "quote": "如果一件事情对你很重要，即使成功的概率很小，你也应该去做",
    "quote_author": "埃隆马斯克",
    
    // Footer
    "copyright": "© 2019 - 2025",
    "disclaimer": "资源来源于网络，如有侵权，请联系客服予以删除！",
    "friendly_links": "友情链接：",
    
    // Language switcher
    "language": "语言",
    "english": "English",
    "french": "Français",
    "chinese": "中文",
    
    // About page
    "about_title": "关于我们",
    "about_subtitle": "专业的 M3U8 流媒体播放器开发团队，致力于为用户提供最佳的观看体验",
    "our_story": "我们的故事",
    "story_content_1": "M3U8 播放器项目始于 2019 年，当时我们注意到市场上缺乏一个简单易用、功能强大的 M3U8 流媒体播放器。",
    "story_content_2": "我们的团队由经验丰富的开发者组成，专注于创建用户友好的工具，让任何人都能轻松播放 M3U8 格式的媒体文件。",
    "story_content_3": "经过多年的开发和优化，我们不断改进产品功能，确保兼容性和稳定性，为用户提供最佳的观看体验。",
    "our_mission": "我们的使命",
    "mission_content_1": "我们的使命是简化 M3U8 流媒体的播放体验，让技术不再成为用户享受高质量媒体内容的障碍。",
    "mission_content_2": "我们致力于开发开源、免费的工具，支持多种格式，确保跨平台兼容性，为用户提供专业级的播放体验。",
    "mission_content_3": "通过持续创新和用户反馈，我们不断优化产品，让 M3U8 播放器成为流媒体播放的首选工具。",
    "key_features": "核心特性",
    "feature_speed": "高速播放",
    "feature_speed_desc": "优化的播放引擎，确保流畅的观看体验",
    "feature_compatibility": "广泛兼容",
    "feature_compatibility_desc": "支持多种浏览器和设备，跨平台兼容",
    "feature_customization": "高度可定制",
    "feature_customization_desc": "丰富的设置选项，满足个性化需求",
    "development_team": "开发团队",
    "team_description": "我们的团队由热爱技术的开发者组成，拥有丰富的流媒体和 Web 开发经验。我们相信开源的力量，致力于为社区贡献优质的工具。",
    "team_role_1": "前端开发",
    "team_role_1_desc": "用户体验专家",
    "team_role_2": "后端开发",
    "team_role_2_desc": "系统架构师",
    "team_role_3": "产品设计",
    "team_role_3_desc": "用户体验设计师",
    "contact_us": "联系我们",
    "contact_description": "如果您有任何问题、建议或反馈，欢迎与我们联系。我们重视每一位用户的意见。",
    "email_us": "发送邮件",
    "github": "GitHub",
    
    // Privacy page
    "privacy": "隐私政策",
    "privacy_title": "隐私政策",
    "privacy_subtitle": "我们重视您的隐私，本政策说明我们如何收集、使用和保护您的个人信息",
    "last_updated": "最后更新：2024年12月",
    "information_collection": "信息收集",
    "collection_content_1": "我们收集的信息类型包括：",
    "collection_item_1": "使用数据：我们收集您如何使用我们服务的信息，包括访问时间、页面浏览等",
    "collection_item_2": "设备信息：浏览器类型、操作系统版本、设备标识符等",
    "collection_item_3": "日志信息：服务器日志、错误报告等",
    "collection_content_2": "我们不会收集您的个人身份信息，如姓名、地址、电话号码或电子邮件地址，除非您主动提供。",
    "information_usage": "信息使用",
    "usage_content_1": "我们使用收集的信息来：提供和改进服务、处理用户请求、发送重要通知等。",
    "usage_content_2": "我们承诺不会将您的个人信息出售、出租或与第三方共享，除非获得您的明确同意。",
    "usage_content_3": "在必要时，我们可能会与法律要求或保护用户权益相关的第三方共享信息。",
    "information_sharing": "信息共享",
    "sharing_content_1": "我们不会出售、交易或以其他方式转让您的个人信息给第三方，除非：",
    "sharing_item_1": "获得您的明确同意",
    "sharing_item_2": "法律要求或政府机构要求",
    "sharing_item_3": "保护我们的权利、财产或安全",
    "sharing_content_2": "我们可能与可信的第三方服务提供商共享信息，这些提供商帮助我们运营网站和提供服务。",
    "data_security": "数据安全",
    "security_content_1": "我们实施适当的技术和组织安全措施来保护您的信息，包括：",
    "security_item_1": "使用加密技术保护数据传输",
    "security_item_2": "定期安全评估和更新",
    "security_item_3": "限制员工访问个人信息的权限",
    "security_item_4": "监控和检测安全威胁",
    "security_content_2": "虽然我们努力保护您的信息，但请注意互联网传输或电子存储方法并非100%安全。",
    "cookies_usage": "Cookie 使用",
    "cookies_content_1": "我们使用 Cookie 和类似技术来：",
    "cookies_item_1": "记住您的偏好设置",
    "cookies_item_2": "分析网站流量和使用模式",
    "cookies_item_3": "提供个性化体验",
    "cookies_item_4": "改进我们的服务",
    "cookies_content_2": "您可以通过浏览器设置控制 Cookie 的使用，但禁用某些 Cookie 可能会影响网站功能。",
    "third_party_services": "第三方服务",
    "third_party_content_1": "我们的服务可能包含第三方链接或服务，包括：",
    "third_party_item_1": "分析服务（如 Google Analytics）",
    "third_party_item_2": "社交媒体插件",
    "third_party_item_3": "支付处理服务",
    "third_party_content_2": "这些第三方服务有自己的隐私政策，我们不对其隐私实践负责。建议您阅读这些第三方服务的隐私政策。",
    "children_privacy": "儿童隐私",
    "children_content_1": "我们的服务不面向13岁以下的儿童。我们不会故意收集13岁以下儿童的个人信息。",
    "children_content_2": "如果您是父母或监护人，并且您知道您的孩子向我们提供了个人信息，请联系我们。如果我们发现我们收集了13岁以下儿童的个人信息，我们将采取措施删除这些信息。",
    "privacy_rights": "您的隐私权利",
    "rights_content_1": "根据适用法律，您可能拥有以下权利：",
    "rights_item_1": "访问我们持有的关于您的个人信息",
    "rights_item_2": "更正不准确或不完整的个人信息",
    "rights_item_3": "删除您的个人信息",
    "rights_item_4": "限制或反对处理您的个人信息",
    "rights_item_5": "数据可携带性",
    "rights_content_2": "要行使这些权利，请通过本政策末尾提供的联系方式联系我们。",
    "policy_changes": "政策变更",
    "changes_content_1": "我们可能会不时更新本隐私政策。当我们进行重大变更时，我们将：",
    "changes_item_1": "在我们的网站上发布更新后的政策",
    "changes_item_2": "更新\"最后更新\"日期",
    "changes_item_3": "在适当情况下通过电子邮件通知您",
    "changes_content_2": "建议您定期查看本政策以了解任何变更。继续使用我们的服务表示您接受更新后的政策。",
    "contact_privacy": "隐私问题联系",
    "contact_privacy_desc": "如果您对本隐私政策有任何问题或疑虑，请通过以下方式联系我们：",
    "email": "邮箱：",
    "response_time": "响应时间：",
    "response_time_desc": "我们将在收到您的请求后48小时内回复",

    // 关于页面新增
    "feature_1": "支持多种视频格式",
    "feature_2": "跨平台兼容性",
    "feature_3": "高清流媒体支持",
    "feature_4": "用户友好界面",
    "team_content_1": "我们的开发团队由经验丰富的工程师组成，专注于前端技术、流媒体技术和用户体验设计。",
    "team_content_2": "我们持续关注技术发展趋势，不断优化产品性能，确保用户获得最佳的观看体验。",
    "team_content_3": "通过开源协作和社区反馈，我们不断完善产品功能，为用户提供更好的服务。",
    "contact_content": "如果您有任何问题或建议，欢迎通过以下方式联系我们：",
    "discord": "Discord",

    // 隐私页面新增
    "user_rights": "用户权利",
    "privacy_contact_content": "如果您对我们的隐私政策有任何疑问或需要行使您的权利，请通过以下方式联系我们：",
    "privacy_email": "隐私邮箱",
    "support_email": "支持邮箱",
    "collection_content_3": "使用数据包括：访问时间、使用功能、错误日志等，用于改进产品和服务质量。",
    "security_content_3": "尽管我们采取了合理的安全措施，但无法保证100%的安全性，我们会持续改进安全防护。",
    "rights_content_3": "在某些情况下，我们可能需要验证您的身份才能处理相关请求"
};
